package com.tsiBahmanFarhang.MicroServiceProjectApplication.SeleniumTest;
// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

    public class ActorSeleniumTest {
        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @Before
        public void setUp() {
            System.setProperty("webdriver.chrome.driver","C:\\Users\\Morgan Smith\\Downloads\\chromedriver_win32 (1)\\chromedriver.exe");
            driver = new ChromeDriver();
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
        @After
        public void tearDown() {
            driver.quit();
        }
        public String waitForWindow(int timeout) {
            try {
                Thread.sleep(timeout);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            Set<String> whNow = driver.getWindowHandles();
            Set<String> whThen = (Set<String>) vars.get("window_handles");
            if (whNow.size() > whThen.size()) {
                whNow.removeAll(whThen);
            }
            return whNow.iterator().next();
        }
        @Test
        public void actorTest() {
            driver.get("http://localhost:3000/");
            driver.manage().window().setSize(new Dimension(1192, 776));
            driver.findElement(By.cssSelector(".search:nth-child(1) input")).click();
            driver.findElement(By.cssSelector(".search:nth-child(1) input")).sendKeys("d");
            vars.put("window_handles", driver.getWindowHandles());
            driver.findElement(By.cssSelector(".dataItem:nth-child(1) > p")).click();
            vars.put("win657", waitForWindow(2000));
            vars.put("root", driver.getWindowHandle());
            driver.switchTo().window(vars.get("win657").toString());
            driver.close();
            driver.switchTo().window(vars.get("root").toString());
            driver.findElement(By.cssSelector(".search:nth-child(1) input")).click();
            driver.findElement(By.cssSelector("#clearBtn > path")).click();
        }
    }

