package com.tsiBahmanFarhang.MicroServiceProjectApplication.SeleniumTest;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.events.EventFiringWebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.*;

public class FilmFinderTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","C:\\Users\\Morgan Smith\\Downloads\\chromedriver_win32 (1)\\chromedriver.exe");
        driver = new ChromeDriver();

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void findFilmTest() throws InterruptedException {
        driver.get("http://localhost:3000");
        Thread.sleep(1000);
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).click();
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).clear();
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).sendKeys("tru");
        //driver.findElement(By.cssSelector(".search:nth-child(2) input")).sendKeys(Keys.BACK_SPACE);
        driver.findElement(By.id("searchBtn")).click();
        driver.findElement(By.id("clearBtn")).click();
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).click();
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).sendKeys("tru");
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector(".dataItem:nth-child(1) > p")).click();
        vars.put("win4443", waitForWindow(2000));
        driver.switchTo().window(vars.get("win4443").toString());

        {
            WebElement element = driver.findElement(By.linkText("WhatCulture"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
    }
}
