package com.tsiBahmanFarhang.MicroServiceProjectApplication.SeleniumTest;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class FilmSeleniumTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","C:\\Users\\Morgan Smith\\Downloads\\chromedriver_win32 (1)\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void filmTest() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1192, 776));
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).click();
        driver.findElement(By.cssSelector(".search:nth-child(2) input")).sendKeys("go");
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("ACE GOLDFINGER")).click();
        vars.put("win8317", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win8317").toString());
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.findElement(By.cssSelector("#clearBtn > path")).click();
    }
}

