//package com.tsiBahmanFarhang.MicroServiceProjectApplication;// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.JavascriptExecutor;
//
//import java.util.*;
//
//public class ActorFilmTestTest {
//    private WebDriver driver;
//    private Map<String, Object> vars;
//    JavascriptExecutor js;
//    @Before
//    public void setUp() {
//        System.setProperty("webdriver.chrome.driver","C:\\Users\\Morgan Smith\\Downloads\\chromedriver_win32 (1)\\chromedriver.exe");
//        driver = new ChromeDriver();
//        js = (JavascriptExecutor) driver;
//        vars = new HashMap<String, Object>();
//    }
//    @After
//    public void tearDown() {
//        driver.quit();
//    }
//    public String waitForWindow(int timeout) {
//        try {
//            Thread.sleep(timeout);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
//        Set<String> whNow = driver.getWindowHandles();
//        Set<String> whThen = (Set<String>) vars.get("window_handles");
//        if (whNow.size() > whThen.size()) {
//            whNow.removeAll(whThen);
//        }
//        return whNow.iterator().next();
//    }
//    @Test
//    public void actorFilmTest() {
//        driver.get("http://localhost:3000/");
//        driver.manage().window().setSize(new Dimension(1552, 840));
//        driver.findElement(By.cssSelector(".search:nth-child(1) input")).click();
//        driver.findElement(By.cssSelector(".search:nth-child(1) input")).sendKeys("t");
//        vars.put("window_handles", driver.getWindowHandles());
//        driver.findElement(By.cssSelector(".dataItem:nth-child(2) > p")).click();
//        vars.put("win7978", waitForWindow(2000));
//        vars.put("root", driver.getWindowHandle());
//        driver.switchTo().window(vars.get("win7978").toString());
//        driver.close();
//        driver.switchTo().window(vars.get("root").toString());
//        driver.findElement(By.cssSelector("#clearBtn > path")).click();
//        driver.findElement(By.cssSelector(".search:nth-child(2) input")).click();
//        driver.findElement(By.cssSelector(".search:nth-child(2) input")).sendKeys("god");
//        vars.put("window_handles", driver.getWindowHandles());
//        driver.findElement(By.cssSelector("p")).click();
//        vars.put("win2084", waitForWindow(2000));
//        driver.switchTo().window(vars.get("win2084").toString());
//        {
//            WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(4) > #dismissible > #root .title-text"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
//        {
//            WebElement element = driver.findElement(By.tagName("body"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element, 0, 0).perform();
//        }
//        js.executeScript("window.scrollTo(0,404.79998779296875)");
//        driver.close();
//        driver.switchTo().window(vars.get("root").toString());
//        driver.findElement(By.id("clearBtn")).click();
//    }
//}
